sudo: false
language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - libunbound-dev
    - libidn11-dev
    - check
    - libevent-dev
    - libev-dev
    - valgrind
    - clang
    - wget
script:
  - mkdir tests
  - cd tests
  - ../src/test/tpkg/run-all.sh
